model: 'coco'
network: 'ro_34' # Syntax: arch_numOfLayers
task: 'circle_snake' # Determines which network to call
resume: true
gpus: (0,) # Must be a tuple

train:
    optim: 'adam'
    lr: 1e-4
    milestones: (80, 120, 150, 170)
    gamma: 0.5
    batch_size: 2
    dataset: 'CocoTrain'
    num_workers: 0

    # FIXME - Revert to number of cores for training
    epoch: 200
test:
    dataset: 'CocoVal'
    batch_size: 1

#heads: {'ct_hm': 1, 'cl': 1, 'reg': 2}
heads: {'ct_hm': 1, 'radius': 1, 'reg': 2}
segm_or_bbox: 'segm' # FIXME - Revert to segm
